### ISSUE TITLE
I don't understand why this dependency is not loaded

### ISSUE THREAD

**Issue by Ayutac** [Ladysnake/Cardinal-Components-API#102]
![excerpt](https://user-images.githubusercontent.com/7873396/143659119-a5abb264-0dd0-4ce6-96d6-863a5aa88256.png)
 This is what I have. I tried all 4 combinations of modApi/modImplementation and with/without include, after each time running build again. build doesn't complain. However, I do not get any suggestions for Component or import dev. when I ask Idea, and searching in the external resources shows no Component interface.

What am I missing? (I'm new to gradle AND Idea, so it might be something obvious)

**Comment by Ayutac** [comment]
Okay, it seems to work when I load module by module.

**Comment by UpcraftLP** [comment]
No idea what you mean by "this" because that screenshot is unreadable, but guess you already fixed it
