### ISSUE TITLE
Cardinal components API 4.0.0 jar seems to be missing modules

### ISSUE THREAD

**Issue by barribob** [Ladysnake/Cardinal-Components-API#105]
The jar on curseforge seems to have only two modules inside of it, whereas the 3.1.1 version has all of the modules. I don't see anything about this on the changelog, so not sure exactly what is going on. Do we need to download all of the individual modules from now on?

**Comment by UpcraftLP** [comment]
it in fact doesn't have any of CCA's modules, thanks for catching that.

seems like loom changed stuff and broke the CI pipeline

**Comment by skerit** [comment]
@UpcraftLP I fixed some 1.18 release changes in my fork (https://github.com/skerit/Cardinal-Components-API/commit/cf4e5713ac51ee4750a08f3632cbffdd1bf4f701) but when I build the project I don't get any usable jars.

Is this related?

**Comment by skerit** [comment]
@UpcraftLP @miyo6032 I reverted the changes in the `build.gradle` script to the ones from this commit: https://github.com/OnyxStudios/Cardinal-Components-API/blob/585360f93d8172ba8f69ce75580112a98f9a3baa/build.gradle, now assembling the project works again. Tests don't want to run though, so I have to use the `gradle assemble` tasks to get the jar.

**Comment by copygirl** [comment]
I just want to note I also ran into this trying to install [Victus](https://modrinth.com/mod/victus) in our modpack.

**Comment by copygirl** [comment]
Is this fixed with the release of 4.0.1?

**Comment by Aquaeyes** [comment]
You say the release of 4.0.1, but the .jar is incorrect (it _only_ contains META-INF) on github and it's not available on curseforge either, so there's no way to check.

**Comment by Pyrofab** [comment]
Should be fine now
