### ISSUE TITLE
Chunk Components don't save

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Cardinal-Components-API#108]
Versions:
**Cardinal Components API**: 4.0.1
**Minecraft**: 1.18.1

While updating a mod that had a cca chunk component to 1.18, I noticed that none of its values persisted between world reloads, I was marking the chunk as unsaved (`Chunk#setShouldSave`), as instructed by the documentation, and still was not working.

[Test mod I made to test the issue](https://github.com/alkyaly/cca-test)
[Log of test](https://gist.github.com/alkyaly/ba3b90392b02b9cf37f508c5ddc25872) (Relevant Lines: 220-222 & 276-278)

As can be seen in the log, [on the second join the `thing` value was 0](https://github.com/alkyaly/cca-test/blob/master/src/main/java/net/fabricmc/example/ExampleMod.java) even though the first join sets the value to 1337.

**Comment by bemk** [comment]
Cardinal Components API: 4.0.1
Minecraft: 1.18.1
Java: openjdk-17

I'm experiencing the same issue with a mod of mine. I took a look at the NBT of the test mod made by @alkyaly, and it looks like the NBT data has shifted a bit between Minecraft versions so maybe that has something to do with it.

A chunk generated with mc-1.18.1, CC 4.0.1:
![image](https://user-images.githubusercontent.com/676740/148601763-65991968-33dd-4d2e-a2b5-848cc6256328.png)

And a chunk generated with 1.17, CC 3.1.1:
![image](https://user-images.githubusercontent.com/676740/148602160-3c0c27ac-b578-454a-b9f8-51c366689251.png)

**Comment by bemk** [comment]
I've also just identified that the serialisation mixin for chunk storage is still trying to look for the "Level" tag.

https://github.com/OnyxStudios/Cardinal-Components-API/blob/f1348735974d025d480fadba49719141db1ff92c/cardinal-components-chunk/src/main/java/dev/onyxstudios/cca/mixin/chunk/common/MixinChunkSerializer.java#L46

https://github.com/OnyxStudios/Cardinal-Components-API/blob/f1348735974d025d480fadba49719141db1ff92c/cardinal-components-chunk/src/main/java/dev/onyxstudios/cca/mixin/chunk/common/MixinChunkSerializer.java#L53

Not entirely sure what these methods have access to, as they're mixins and I was using CC to avoid having to use them in the first place. Hope this is helpful in fixing the issue though!

**Comment by apace100** [comment]
I also ran into the same issue. After some investigation, I found out that the chunks used for initialization of the components are `ReadOnlyChunk`s, thus their `setShouldSave` method does nothing.

**Comment by bemk** [comment]
Just added a potential fix to a merge request, but I haven't tested the reading of the tag yet. I'm also aware that there is no adapter yet that would allow the data from an older version to persist into the current one.

**Comment by Pyrofab** [comment]
If I'm not mistaken, mojang's data fixer should preserve the old data so there should not be an issue
