### ISSUE TITLE
No Icon

### ISSUE THREAD

**Issue by Jab125** [Ladysnake/Cardinal-Components-API#109]
There is no icon for cardinal components, i've attached an image (that need resizing)
![cardinal_components](https://user-images.githubusercontent.com/67534807/148722018-a39eda09-5e8f-4368-b1cb-fdff88026d7b.png)

Edit: image created by modifying the svg

**Comment by Pyrofab** [comment]
Thanks for the reminder ! I ended up going with a pixel art recreation as I got a bit concerned about file size.
