### ISSUE TITLE
Upload correct 4.0.1 release jar

### ISSUE THREAD

**Issue by mrmelon54** [Ladysnake/Cardinal-Components-API#111]
The 4.0.1 release jar is only 261 bytes which quite clearly doesn't contain the required compiled class files for this mod to function. Please can you upload the correct jar.

**Comment by TristanKing0** [comment]
Almost a week and nothing? 4.0 is unusable as it crashes due to the chunk issue.

**Comment by mrmelon54** [comment]
You can try this build

https://github.com/MrMelon54/Cardinal-Components-API/releases/tag/4.0.1

**Comment by mrmelon54** [comment]
well its been 2 weeks now any updates?

**Comment by Plastogerm** [comment]
Yes, please update this. I'm holding off on starting my server with friends as one of the fun mods requires this API to be installed, and we cannot upload user-made builds on Aternos. :disappointed:

**Comment by mrmelon54** [comment]
There is a version 4.1.0 that you could try...

**Comment by Plastogerm** [comment]
@MrMelon54 it just does not work, the creators changing the maven group is what made me want to downgrade to 4.0.1. As [PlayerEx](https://www.curseforge.com/minecraft/mc-mods/playerex) crashes the server with the 4.1.0 version of CC API on Curseforge.

**Comment by mrmelon54** [comment]
well the version of 4.0.1 which is available is way too small to contain the required files and thus is completely useless

**Comment by Plastogerm** [comment]
Yeah, so we'll just.. wait.

**Comment by Pyrofab** [comment]
Apologies, the buildscript got very much broken during the loom update. I believe 4.1.2 should fix the aforementioned issues.
