### ISSUE TITLE
Victus Requesting cardinal-components-entity 4.0.0

### ISSUE THREAD

**Issue by HypnoticChris** [Ladysnake/Cardinal-Components-API#112]
This may be a problem with the Victus mod, but it is asking for a version of this mod that I couldn't find anywhere on curseforge or on the GitHub, it keeps crashing with the error "Mod 'Victus' (victus) 0.1.4+1.18 requires version 4.0.0 or later of cardinal-components-entity, which is missing!" I downloaded 4.0.1 and 4.0.0 from the github and neither of those worked, any help?

**Comment by Pyrofab** [comment]
Hi and sorry for the delay ! I believe the latest curseforge versions should work, could you confirm ?
