### ISSUE TITLE
Add callback for when component is destroyed

### ISSUE THREAD

**Issue by AlphaMode** [Ladysnake/Cardinal-Components-API#120]
After trying to convert my forge cap's to use cca I was looking for a alternative for a callback for when the component is destroyed
the closest thing I could find is RespawnCopyStrategy which is not what I want

**Comment by Pyrofab** [comment]
Could you describe your use case ? There may be other ways to achieve what you want, but if you are looking for an entity unload event you can use `ServerEntityEvents.ENTITY_UNLOAD` from Fabric API.

**Comment by Pyrofab** [comment]
@AlphaMode does this seem good to you ? <https://github.com/OnyxStudios/Cardinal-Components-API/tree/1.20/cardinal-components-base/src/main/java/dev/onyxstudios/cca/api/v3/component/load>
