### ISSUE TITLE
Maven dependency not importing API

### ISSUE THREAD

**Issue by SabrinaIsHere** [Ladysnake/Cardinal-Components-API#123]
I followed the instructions laid out in the wiki and couldn't get the api to import using maven, it will build and launch if only `base` is included but I can't access any of the api code even if it builds, including any modules makes it throw the same stacktrace. Attached are the relevant screenshots and stacktraces.

**Building Successfully:**
![maven_dependency](https://user-images.githubusercontent.com/74331139/159710488-2dd956e7-3ec2-4f94-b530-5d50362939ec.png)
![stacktrace (successful)](https://user-images.githubusercontent.com/74331139/159710603-327fdf77-e258-42f4-b6b1-f4c44d35bf2d.png)
**Not Building:**
![maven_dependency_(not compiling)](https://user-images.githubusercontent.com/74331139/159710709-b5a1c3cc-0c2e-4769-bb34-3614e5730b14.png)
![stacktrace (failed)](https://user-images.githubusercontent.com/74331139/159710874-6e16e3cc-4f41-4701-8df2-2c8cae3dfc2d.png)

I'm not very well versed in this stuff but I double checked everything and I really don't know why this is happening, so thanks in advance

**Comment by PTOM76** [comment]
Mee to.

For the time being, I tried to place the repository locally.
I want the mod developer to fix it ^^;

- build.gradle
```gradle
repositories {
    mavenLocal()
    ...
}
```
Put the contents of the following two zip files in the specified folder. (The folder to put in may depend on the settings.)
- 1. C:\Users\<User Name>\.m2\repository\io\github\onyxstudios\Cardinal-Components-API\
[pom_4.1.4.zip](https://github.com/OnyxStudios/Cardinal-Components-API/files/8397412/pom_4.1.4.zip)

- 2. C:\Users\<User Name>\.gradle\caches\fabric-loom\4.1.4
[fabric-loom_4.1.4.zip](https://github.com/OnyxStudios/Cardinal-Components-API/files/8397414/fabric-loom_4.1.4.zip)

**Comment by Pyrofab** [comment]
Which version of Loom are you using ?

**Comment by blacksabin** [comment]
Having the same issue here. Builds fine with just using cardinal-components-base, but as soon as I include any other module (namely entity) I receive the same error output. I've tweaked around trying many different versions that other mods seem to use in tandem with Cardinal Components, but I have yet to get any of it to work. Is this user error, or something missing on Cardinal Component's side?
