### ISSUE TITLE
crash on On world start 

### ISSUE THREAD

**Issue by timtornado** [Ladysnake/Cardinal-Components-API#125]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 6/17/22, 9:28 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'dev.onyxstudios.cca.api.v3.component.ComponentProvider dev.onyxstudios.cca.api.v3.component.ComponentProvider.fromEntity(net.minecraft.class_1297)'
	at net.minecraft.class_3324.md380745$lambda$syncPowerTypes$1$0(class_3324.java:1501)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraft.class_3324.handler$zem000$syncPowerTypes(class_3324.java:1500)
	at net.minecraft.class_3324.method_14570(class_3324.java:282)
	at net.minecraft.class_3248.method_33800(class_3248.java:130)
	at net.minecraft.class_3248.method_14384(class_3248.java:117)
	at net.minecraft.class_3248.redirect$doo000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:67)
	at net.minecraft.class_2535.method_10754(class_2535.java:243)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:918)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1841033200 bytes (1755 MiB) / 4211081216 bytes (4016 MiB) up to 9160359936 bytes (8736 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i7-12700K
	Identifier: Intel64 Family 6 Model 151 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 3.61
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 20
	Graphics card #0 name: spacedesk Graphics Adapter
	Graphics card #0 vendor: datronicsoft
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: DriverVersion=1.1.352.157
	Graphics card #1 name: NVIDIA GeForce RTX 3060
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x2504
	Graphics card #1 versionInfo: DriverVersion=31.0.15.1640
	Graphics card #2 name: vs spacedesk Graphics Adapter
	Graphics card #2 vendor: datronicsoft
	Graphics card #2 VRAM (MB): 0.00
	Graphics card #2 deviceId: unknown
	Graphics card #2 versionInfo: DriverVersion=1.1.352.157
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Virtual memory max (MB): 61253.42
	Virtual memory used (MB): 40267.65
	Swap memory total (MB): 20480.00
	Swap memory used (MB): 2339.81
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8736m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.4
		additionalbars: Additional Bars 3.0.0
		additionalstructures: Additional Structures 3.0.3
		adorn: Adorn 3.5.0+1.18.2
		advancements-enlarger: Advancements Enlarger 0.2.4
		advdebug: Advancements Debug 2.3.0
		adventurez: AdventureZ 1.4.11
		all_the_fan_made_discs: All The Fan Made Discs 0.2.4
		aqupdcaracal: Caracal mob 1.18.2-1.3.8
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		arcanus: Arcanus 1.29
		architects_palette: Architect's Palette Fabric 2.1
		architectury: Architectury 4.4.70
		artifacts: Artifacts 7.0.3+fabric
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		attributefix: AttributeFix 14.0.2
		autoconfig1u: Auto Config v1 Updated 3.4.0
		auudio: Auudio 1.0.3
		axolotlitemfix: Axolotl Item Fix 1.1.3
		backslot: BackSlot 1.2.6
			amecsapi: Amecs API 1.3.5+mc22w06a
		backslotaddon: BackSlot Addon 1.0.8
		badpackets: Bad Packets 0.1.2
		balm-fabric: Balm 3.0.0+0
		basicshields: Basic Shields [Fabric] 1.3.1-1.18.2
			crowdin-translate: CrowdinTranslate 1.4+1.18.2
		bcc: BetterCompatibilityChecker fabric-1.0.5
		bclib: BCLib 1.4.7
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.1
		betterf3: BetterF3 1.2.5
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.3
		betternether: Better Nether 6.1.2
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		betterthirdperson: Better Third Person 1.7.3
		bewitchment: Bewitchment 1.18-22
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			playerabilitylib: Pal 1.5.0
			reach-entity-attributes: Reach Entity Attributes 2.1.1
			terraform-wood-api-v1: Terraform Wood API (v1) 3.0.0
		bhmenu: BHMenu-Fabric 1.17.1-1.18.2-1.3
		biomeinfo: BiomeInfo 1.18.2-10
		biomemakeover: Biome Makeover 1.18.2-1.4.24
		bitsandchisels: BitsAndChisels 2.6.9
			stacc: Stacc 1.2.3
		blockus: Blockus 2.4.7+1.18.2
		blur: Blur (Fabric) 2.4.1
		boatcontainer: BoatContainer 1.1.0
		bookshelf: Bookshelf 13.2.20
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
			maelstrom_library: Maelstrom Library 1.2.4-1.18.2
			multipart_entities: MultipartEntities 1.1.5-1.18.2
		bucolicorigins: Bucolic_Origins[FABRIC] 3.1
		byg: Oh The Biomes You'll Go 1.4
		capybara: Capybara 1.0.4
		cardinal-components: Cardinal Components API 4.1.4
			cardinal-components-block: Cardinal Components API (blocks) 4.1.4
			cardinal-components-entity: Cardinal Components API (entities) 4.1.4
			cardinal-components-item: Cardinal Components API (items) 4.1.4
			cardinal-components-level: Cardinal Components API (world saves) 4.1.4
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		carrier: Carrier 1.10.0
			advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		celib: Celib 1.0.0
		charm: Charm 4.1.2
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		cherishedworlds: Cherished Worlds 2.0.1-1.18
		chipped: Chipped 1.2
		chubby_stuff: Chubby Stuff 1.0.1
		clienttweaks: Client Tweaks 7.1.0
		cloth-api: Cloth API 3.2.64
			cloth-client-events-v0: Cloth Client Events v0 3.2.64
			cloth-common-events-v1: Cloth Common Events v1 3.2.64
			cloth-datagen-api-v1: Cloth Datagen v1 3.2.64
			cloth-scissors-api-v1: Cloth Scissors API v1 3.2.64
			cloth-utils-v1: Cloth Utils v1 3.2.64
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 8.0.0+8
		collective-fabric: Collective (Fabric) 4.27
			fiber: fiber 0.23.0-2
		comforts: Comforts 1.1.2-1.18.2
		continuity: Continuity 2.0.0+1.18.2
		controlling: Controlling For Fabric 9.0+19
		cosmetic-armor: Cosmetic Armor 1.3.1
		couplings: Couplings 1.8.0+1.18.2
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		crafttweaker: CraftTweaker 9.1.153
			org_javassist_javassist: javassist 3.29.0-GA
			org_reflections_reflections: reflections 0.10.2
		crawl: Crawl 0.10.6
			mm: Manningham Mills 2.3
		creatures_from_the_warmths: Creatures From The Warmths 2.1.0+1.18.2
		creeperoverhaul: Creeper Overhaul 1.3.1
		cullleaves: Cull Leaves 2.3.2
		darkpaintings: DarkPaintings 10.0.3
		dashloader: DashLoader 4.0.0
			com_github_luben_zstd-jni: zstd-jni 1.5.2-2
			dev_quantumfusion_hyphen: Hyphen 0.2.2
			dev_quantumfusion_taski: Taski 1.1.0
		dawn: Dawn API 3.3.1
		decorative_blocks: Decorative Blocks 2.1.0
		deepslatecutting: Deepslate Cutting 1.3.4
			maybe-data: Maybe data 1.3.1-1.18.2
		deleteworldstotrash: Delete Worlds To Trash 3.2.0
		dragonloot: DragonLoot 1.1.0
		dramaticdoors: Dramatic Doors (Fabric) 1.18.2-1.1.1
		drippyloadingscreen: Drippy Loading Screen 1.6.3
		duckling: Duckling 1.0.5
		dummmmmmy: MmmMmmMmmMmm 1.18-1.5.0
		dustrial_decor: Dustrial Decor 0.5
		dynamicfps: Dynamic FPS 2.1.0
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easyshulkerboxes: Easy Shulker Boxes 3.1.1
		eatinganimationid: Eating Animation 1.8
		ecologics: Ecologics 1.5.4
		edenring: EdenRing 0.5.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchant_the_rainbow: Enchant the Rainbow 1.0.1
		enchantment_lore: Enchantment Lore 1.2.6-1
		enchdesc: EnchantmentDescriptions 10.0.3
		endgoblintraders: End Goblin Traders 1.5 (Re-upload)
		enhanced_attack_indicator: Enhanced Attack Indicator 1.0.3+1.18
		enhancedcelestials: Enhanced Celestials 2.0.7
		entityculling: EntityCulling-Fabric 1.5.1
		equipmentcompare: Equipment Compare 1.2.12
		essential_commands: Essential Commands 0.23.0-mc1.18.2
			com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.13.0
			ec-core: Essential Commands Core 1.0.1-mc1.18.2
			placeholder-api: Placeholder API 1.1.3+1.17.1
		expanded_armor_enchanting: Expanded Armor Enchanting 1.0.2
		expanded_axe_enchanting: Expanded Axe Enchanting 1.0.3
		expanded_weapon_enchanting: Expanded Weapon Enchanting 1.0.2
		expandeddelight: Expanded Delight 0.1.9
		experiencebottler: Experience Bottler 1.18.2+build.1
		extended_armor_bars: Extended Armor Bars 1.2.1
		extendedclouds: Extended Clouds 1.1.1
		extra_classes_origins: Extra Classes - Origins 1.0.0
		extraorigins: Extra Origins 1.18-11
		fabric: Fabric API 0.56.0+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.2+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.22+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.1.0+6f01bfd860
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 3.0.0+9fcb91d260
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.18+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.1+6c4e5d0960
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.13+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+cc71601c60
			fabric-loot-api-v2: Fabric Loot API (v2) 1.0.0+e747827960
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.0+e747827960
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.3+cc71601c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.22+e6b169eb60
			fabric-networking-v0: Fabric Networking (v0) 0.3.9+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.2+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.9+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.1+e747827960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.1+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.3+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.0+e747827960
		fabric-language-kotlin: Fabric Language Kotlin 1.8.0+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.17.3
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.2
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricenchantments: Fabric Enchantments 0.7.2
		fabricloader: Fabric Loader 0.14.7
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
		fallingleaves: Falling Leaves 1.11.1+1.18.2
		fallingtree: FallingTree 3.5.1
		fancymenu: FancyMenu 2.7.2
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		faux-custom-entity-data: Faux-Custom-Entity-Data 2.0.1
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		forgeconfigapiport: Forge Config API Port 3.2.0
		forgottenrecipes: ForgottenRecipes 1.18.1-1.0.0
		friendsandfoes: Friends&Foes 1.4.3
		ftbchunks: FTB Chunks 1802.3.6-build.147
		ftblibrary: FTB Library 1802.3.6-build.123
		ftbquests: FTB Quests 1802.3.8-build.101
		ftbteams: FTB Teams 1802.2.6-build.51
		gateofbabylon: Gate Of Babylon 1.7.0-1.18.2
		geckolib3: Geckolib 3.0.47
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.2
		giantspawn-fabric: Giant Spawn (Fabric) 2.7
		go-fish: Go Fish 1.5.0-1.18.2
		goblintraders: Goblin Traders 1.5.1
		goodall: Goodall 1.0.2
		graveyard: The Graveyard 1.9
		guardvillagers: Guard Villagers Fabric 1.18.2-1.0.14
		health_levels: Health Levels 1.0.2
		highlighter: Highlighter 1.1.2
		hoetweaks-fabric: Hoe Tweaks (Fabric) 1.4
		holograms: Holograms 1.3.1+1.18.2
			hologram-api: Hologram API 0.2.1+1.18-pre5
			server_translations_api: Server Translations API 1.4.9+1.18.2-rc1
				packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		hookshot: Hookshot 25.0
		icarus: Icarus 1.11
		iceberg: Iceberg 1.0.38
		immersive_armors: Immersive Armors 1.3.5
		immersive_weathering: Immersive Weathering 2.5.5
		impaled: Impaled 1.1.3
		indium: Indium 1.0.3+mc1.18.2
		infusion_table: Infusion Table 1.1.0
		ingredient-extension-api: Ingredient Extension API 2.0.5
		inmis: Inmis 2.6.0-1.18.2
			omega-config: OmegaConfig 1.2.3-1.18.1
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		ironchests: Iron Chests 1.7.0
			libgui: LibGui 5.4.2+1.18.2
				jankson: Jankson 4.0.0+j1.2.0
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
		itemfilters: Item Filters 1802.2.7-build.21
		jamlib: JamLib 0.0.5
		java: OpenJDK 64-Bit Server VM 17
		kleeslabs: KleeSlabs 11.0.0
		konkrete: Konkrete 1.3.3
		krypton: Krypton 0.1.9
			com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		lambdynlights: LambDynamicLights 2.1.0+1.17
			pride: Pride Lib 1.1.0+1.17
			spruceui: SpruceUI 3.3.0+1.17
				org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		lazydfu: LazyDFU 0.1.2
		lithium: Lithium 0.7.10
		lootgoblins: Lootgoblins 1.0.8
		lovely_snails: Lovely Snails 1.0.4+1.18
		macawsbridgesbyg: Macaw's Bridges - BYG 1.18.2-1.2
		macawsroofsbyg: Macaw's Roofs - BYG 1.18.2-1.0
		magnumtorch: Magnum Torch 3.1.2
		mantori: Aphid Additions 1.0.0-1.18.2
		mavm: More Axolotl Variants Mod 1.0.8a
		mcda: MC Dungeons Armors 2.0.6
		mcdar: MC Dungeons Artifacts 1.4.8
		mcdw: MC Dungeons Weapons 4.4.0
			enchant_giver: Enchant Giver 1.2.1
		mcwbridges: Macaw's Bridges 2.0.3
		mcwdoors: Macaw's Doors 1.0.6
		mcwfences: Macaw's Fences and Walls 1.0.5
		mcwlights: Macaw's Lights and Lamps 1.0.3
		mcwpaintings: Macaw's Paintings 1.0.3
		mcwpaths: Macaw's Paths and Pavings 1.0.0
		mcwroofs: Macaw's Roofs 2.1.2
		mcwwindows: Macaw's Windows 2.0.3
		megane: megane 7.5.1
			megane-api: megane-api 7.1.0
			megane-fabric-transfer: megane-fabric-transfer 7.1.0
			megane-runtime: megane-runtime 7.2.0
			megane-vanilla: megane-vanilla 7.1.1
		midnightlib: MidnightLib 0.4.4
		minecraft: Minecraft 1.18.2
		mob_catcher: Mob Catcher 1.1.26
		modid: Creatures Of The Snow 2.1.0+1.18.2
		modmenu: Mod Menu 3.2.2
		more-axolotls: More Axolotls 1.0.2
		more_babies: More Babies 0.5.2
		moreachievements: MoreAchievements 1.0.8
		moretags: More Tags 3.0.4
		moretotems: More Totems 2.10.0
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		mostructures: Mo' Structures 1.4.2+1.18.2
		mousetweaks: Mouse Tweaks 2.22
		mythicmounts: Mythic Mounts 1.18.2-7.0
		naturescompass: Nature's Compass 1.18.2-2.0.3-fabric
		nears: Nears 1.1.8
		notenoughanimations: NotEnoughAnimations 1.6.0
		onsoulfire: On Soul Fire 1.18-3
		origins: Origins 1.4.1
			apoli: Apoli 2.3.3
				additionalentityattributes: Additionalentityattributes 1.0.0+1.18.2
				calio: Calio 1.5.1
		origins-classes: Origins: Classes 1.3.0
		origins-plus-plus: Origins++ 1.5.3
		oxidized: Oxidized 1.6.4
		paintings: Paintings++ 9.1.2.1
		patchouli: Patchouli 1.18.2-69-FABRIC
		paxi: Paxi 1.18.2-Fabric-2.0
		pehkui: Pehkui 3.3.2+1.14.4-1.19
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		phosphor: Phosphor 0.8.1
		pickupnotifier: Pick Up Notifier 3.2.0
		pigsteel: Pigsteel Mod 1.7.1
		plushies: Plushie Mod 1.2
		polymorph: Polymorph 0.0.21-1.18.2
		postmateria: Post Materia 1.0.0-1.18.2
			fiblib: FibLib 1.3.1+1.18.2
			world-data: World Data 1.0.3-1.18.2
		probablychests: Probably Chests 0.4.3
		puzzle: Puzzle 1.3.0
			puzzle-base: Puzzle Base 1.3.0
			puzzle-gui: Puzzle GUI 1.3.0
			puzzle-models: Puzzle Models 1.3.0
			puzzle-splashscreen: Puzzle Splash Screen 1.3.0
		puzzleslib: Puzzles Lib 3.3.5
		quartzelv: Quartz Elevator 2.1.2+1.18.2
		refabslab: Refabricated Slabs 0.6.2
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.0-beta.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.0-beta.1
		repurposed_structures: Repurposed Structures 4.1.14+1.18.2
		respro: Resource Provider Library 0.1.1
		rightclickharvest: Right Click Harvest 2.0.8
		roughlyenoughitems: Roughly Enough Items 8.2.473
		roughlyenoughprofessions: Roughly Enough Professions 1.0.1
		roughlyenoughresources: Roughly Enough Resources 2.5.0
		rpgdifficulty: Rpg Difficulty 1.0.12
		runelic: Runelic 11.0.1
		seasons: Fabric Seasons 1.4-BETA+1.18
		simple-rpc: Simple RPC 3.0.1
			me_hypherionmc_simple-rpc-common: simple-rpc-common 3.0.1
		simplehats: SimpleHats 1.18.2-0.1.0
		sit: Sit 1.18.2-19
		skinlayers: 3d Skin Layers 1.4.6-mc1.18.2
		skylorlib: SkyLib 1.3.35
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		spark: spark 1.9.11
		spirit: Spirit 1.3.0
		sprout: Sprout 1.3.1
		starterkit-fabric: Starter Kit (Fabric) 3.1
		steves_vanilla: Steves Vanilla 1.1.0+1.18
		stoneholm: Stoneholm 1.4.3
		strawgolem: Straw Golem 2.0.0b1
		styled-nicknames: Styled Nicknames 1.0.4+1.18
			player-data-api: Player Data API 0.1.0+1.18
		styledchat: Styled Chat 1.2.3+1.18
		t_and_t: Towns and Towers - Structure Add-on 1.6
		terrablender: TerraBlender 1.1.0.102
		the_aether: Paradise Lost 1.6.9+1.18.2
			customportalapi: Custom Portal Api 0.0.1-beta50-1.18
			gud_recipe_confidence: Recipe Confidence 1.0.2
			incubus_core: Incubus Core 1.6.6+1.18.2
			satin: Satin 1.7.2
		the_bumblezone: The Bumblezone - Fabric 5.1.2+1.18.2
			fake-player-api: Fake Player API 0.3.0
		thonkutil: ThonkUtil 2.14.1+1.18
			thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
			thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
			thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
			thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
			thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
			thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
			thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
			thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
			thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		toms_storage: Tom's Simple Storage Mod 1.3.2
		totw_additions: Towers of the Wild: Additions 1.2.1
		tradingpost: Trading Post 3.2.0
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch1+1.18.2
		universal_ores: Universal Ores 1.2.1
		universalbonemeal: Universal Bone Meal 3.0.5
		utilities: Utilities 1.5.2
		vanilla_degus: Vanilla Degus 1.3.0
		veinmining: Vein Mining 0.0.12-1.18.2
		villager-hats: Villager Hats 1.4.0
		villagernames: Villager Names 4.0.4
		visuality: Visuality 0.4.2
			goosik-config: goosik-config 0.2.0
			tlcosmetica: Cosmetica 0.4.0
		visualworkbench: Visual Workbench 3.3.0
		voicechat: Simple Voice Chat 1.18.2-2.2.45
		voidtotem: VoidTotem (Fabric) 1.18.2-1.3.1
		voidz: VoidZ 1.0.7
		wandering_collector: Wandering Collector 1.1.2+mc1.18.2
			coat: Coat 1.0.0-beta.17+mc1.18.2
			tweed4_annotated: tweed4_annotated 1.3.0
			tweed4_base: tweed4_base 1.5.0+mc1.18.2
			tweed4_data: tweed4_data 1.2.1+mc1.18.2
			tweed4_data_hjson: tweed4_data_hjson 1.1.0
			tweed4_tailor_coat: tweed4_tailor_coat 1.1.2+mc1.18.2
			tweed4_tailor_screen: tweed4_tailor_screen 1.1.1+mc1.18.2
		waystones: Waystones 2.5.4
		windchimes: Windchimes 1.2.0
		wolveswitharmor: Wolves With Armor 1.7.1-1.18.2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		wthit: wthit 4.10.3
		x-enchant: X-Enchant 1.18-8.8
		xaerominimap: Xaero's Minimap 22.9.2
		xaeroworldmap: Xaero's World Map 1.23.2
		xlpackets: XLPackets 2.1-1.17.1
		yigd: You're in Grave Danger 1.3.4
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
		zihlaunchpads: ZIHLaunchpads 1.2.0
		zoomify: Zoomify 1.6.0
			com_github_llamalad7_mixinextras: mixinextras 0.0.10
			dev_isxander_settxi: settxi 2.1.1
			settxicloth: Settxi Cloth Impl 1.0.2
	Loaded Shaderpack: BSL_v8.1.02.3 (1).zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Tim_Tornada'/232, l='ServerLevel[New World]', x=130.50, y=74.00, z=-153.50]]
	Data Packs: vanilla, Repurposed_Structures-Better_Dungeons_v2.zip (incompatible), Repurposed_Structures-Better_Strongholds_v3.zip, Repurposed_Structures-Bountiful_Fabric.zip (incompatible), Repurposed_Structures-Farmers_Delight_v3.zip (incompatible), Repurposed_Structures-Friends_And_Foes-v1.zip, Repurposed_Structures-More_Villagers_v6.zip, ichphilipp-s-endcity-better-end-1-18-1.zip (incompatible), Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by UpcraftLP** [comment]
refabricated slabs uses a version of cardinal-components that was built for 1.19, not 1.18.
