### ISSUE TITLE
Quilt support

### ISSUE THREAD

**Issue by slava110** [Ladysnake/Cardinal-Components-API#126]
Hi. I'm developing quilt mod with `CardinalComponentsAPI` as dependency but it crashes on loading because CardinalComponents is unable to find `custom` properties. I guess it's because you're using `FabricLoader` here. Do you think it would be possible to support Quilt too? Or should I switch back to Fabric?
https://github.com/OnyxStudios/Cardinal-Components-API/blob/72d0a4fb6fad36bfabb09770cea92da5d4eba74f/cardinal-components-base/src/main/java/dev/onyxstudios/cca/internal/base/asm/CcaBootstrap.java#L87

**Comment by Pyrofab** [comment]
Have you checked the updated readme ? I managed to use CCA on Quilt just fine with a few tweaks to the mod metadata.

**Comment by slava110** [comment]
Oh, it's not in the `custom` section. I'll check it out

**Comment by slava110** [comment]
Yes, it's working now. Thanks!
