### ISSUE TITLE
Client-side crash on 1.19 Fabric server (Medieval MC)

### ISSUE THREAD

**Issue by Kelvin-Raath** [Ladysnake/Cardinal-Components-API#133]
When u tp home with the wand from a diff realm (nether/end) the client completely crashes with this report:

https://pastebin.com/FnwQrRmL

**Comment by Pyrofab** [comment]
Seems to be the same issue as https://github.com/quiqueck/BetterEnd/issues/31, you should be able to fix it by updating BCLib.
