### ISSUE TITLE
This mod crash my game if i create and load world 

### ISSUE THREAD

**Issue by penetratorcwl** [Ladysnake/Cardinal-Components-API#134]
Who mod in my mod pack need cardinal components
This is log:

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 8/19/22 5:58 PM
Description: Exception in server tick loop

java.lang.ExceptionInInitializerError
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.10)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.lambda$createEntityComponentContainer$3(CardinalEntityInternals.java:101)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals$$Lambda$6852/1902605762.apply(Unknown Source)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118)
	at dev.onyxstudios.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:86)
	at net.minecraft.entity.Entity.handler$zel000$initDataTracker(Entity:3185)
	at net.minecraft.entity.Entity.<init>(Entity:263)
	at net.minecraft.entity.LivingEntity.<init>(LivingEntity:219)
	at net.minecraft.entity.player.PlayerEntity.<init>(PlayerEntity:199)
	at net.minecraft.server.network.ServerPlayerEntity.<init>(ServerPlayerEntity:185)
	at net.minecraft.server.PlayerManager.createPlayer(PlayerManager:461)
	at net.minecraft.server.network.ServerLoginNetworkHandler.acceptPlayer(ServerLoginNetworkHandler:113)
	at net.minecraft.server.network.ServerLoginNetworkHandler.redirect$znn000$handlePlayerJoin(ServerLoginNetworkHandler:562)
	at net.minecraft.server.network.ServerLoginNetworkHandler.tick(ServerLoginNetworkHandler:65)
	at net.minecraft.network.ClientConnection.tick(ClientConnection:228)
	at net.minecraft.server.ServerNetworkIo.tick(ServerNetworkIo:173)
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer:882)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at net.minecraft.server.MinecraftServer$$Lambda$6352/1329184930.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Failed to hack fabric API
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:56)
	... 22 more
Caused by: java.lang.NoSuchFieldException: type
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at dev.onyxstudios.cca.internal.base.ComponentsInternals.<clinit>(ComponentsInternals.java:52)
	... 22 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 787785904 bytes (751 MB) / 1535639552 bytes (1464 MB) up to 2863661056 bytes (2731 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3072m -Xms256m
	Suspected Mods: Minecraft (minecraft), Cardinal Components API (entities) (cardinal-components-entity)
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.16.5
		architectury: Architectury 1.32.66
		auudio: Auudio 1.0.3
		betterbiomeblend: Better Biome Blend 1.16.4-1.2.9-fabric
		betterf3: BetterF3 1.1.3
		betterthirdperson: Better Third Person 1.5.0
		blue_endless_jankson: jankson 1.2.1
		blur: Blur (Fabric) 2.1.0
		boostedbrightness: Boosted Brightness 1.2.1
		caelus: Caelus API 0.0.15-1.16.4
		caffeineconfig: CaffeineConfig 1.0.0
		cardinal-components-base: Cardinal Components API (base) 2.7.2
		cardinal-components-entity: Cardinal Components API (entities) 2.7.2
		cardinal-components-item: Cardinal Components API (items) 2.7.2
		chunky: Chunky 1.2.54
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-client-events-v0: Cloth Client Events v0 1.6.59
		cloth-config2: Cloth Config v4 4.14.64
		collective-fabric: Collective (Fabric) 4.36
		com_electronwill_night-config_core: core 3.6.5
		com_electronwill_night-config_toml: toml 3.6.5
		crawl: Crawl 0.8.4
		cullleaves: Cull Leaves 2.1.0
		curios: Curios API 0.0.13-1.16.5
		curiouselytra: Curious Elytra 1.1.1-1.16.5
		customizableelytra: Customizable Elytra 1.5.2-1.16.4
		detailab: Detail Armor Bar 2.6.1+1.16.5-fabric
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		ebf: Experience Bug Fix 1.0.0.1
		enchantedtooltips: Enchanted ToolTips 1.3.5-1.16
		enchdesc: EnchantmentDescriptions 2.0.8
		entityculling: EntityCulling-Fabric 1.5.2
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-language-kotlin: Fabric Language Kotlin 1.7.0+kotlin.1.6.0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricenchantments: Fabric Enchantments 0.4.1
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.6.0+1.16.5
		faster-minecarts: Faster Minecarts 1.0.1
		ferritecore: FerriteCore 2.1.0
		fiber: fiber 0.23.0-2
		flytre_lib: FlytreLib 0.2.11
		forgeconfigapiport: Forge Config API Port 1.0.1
		fpsreducer: FPS Reducer 1.24-mc1.16.5
		freecam: Freecam 1.1.4
		globedimension: Chunk In A Globe 1.16.5-1.1.0
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		illuminations: Illuminations 1.5.1
		indium: Indium 1.0.0+mc1.16.5
		inventoryhud: Inventory HUD + 3.4.1
		iris: Iris 1.2.6
		itemmodelfix: Item Model Fix 1.0.3+1.16
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jespegg: Just Enough SpawnEggs 1.1.0
		kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		konkrete: Konkrete 1.3.3
		kyrptconfig: Kytpt Config 1.1.8-1.16
		lazydfu: LazyDFU 0.1.2
		lchunkloader: Literally Chunk Loader 2.0.3
		libgui: LibGui 3.2.2+1.16.3
		litematica: Litematica 0.0.0-dev.20210917.192300
		lithium: Lithium 0.6.6
		malilib: MaLiLib 0.10.0-dev.21+arne.8
		minecraft: Minecraft 1.16.5
		mm: Manningham Mills 2.2
		mocap: Motion Capture Mod (mocap) 1.0
		modmenu: Mod Menu 1.16.23
		mousetweaks: Mouse Tweaks 2.22
		namepain: Name Pain 1.4.0
		noenchantcap: NoEnchantCap 4.1.0
		notenoughanimations: NotEnoughAnimations 1.2.4
		notenoughcrashes: Not Enough Crashes 4.1.4+1.16.5
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.0
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.1
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.1
		org_slf4j_slf4j-api: slf4j-api 1.7.12
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
		phosphor: Phosphor 0.8.0
		quartzelv: Quartz Elevator 1.3.0+1.16
		quickshulker: Quick Shulker 1.1.14-1.16
		reeses-sodium-options: Reese's Sodium Options 1.4.6+mc1.16.5-build.52
		roughlyenoughitems: Roughly Enough Items 5.12.385
		roughlyenoughitems-api: REI (API) 5.12.385
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.12.385
		roughlyenoughitems-runtime: REI (Runtime) 5.12.385
		satin: Satin 1.5.1
		shulkerboxtooltip: Shulker Box Tooltip 2.3.8+1.16.5
		shulkerdropstwo-fabric: Shulker Drops Two (Fabric) 2.1
		shulkerutils: shulkerutils 1.0.1-1.16
		silktouch_spawners: SilkTouch Spawners 0.0.1
		skinlayers: 3d Skin Layers 1.1.0
		smoothboot: Smooth Boot 1.16.5-1.6.0
		snowballsfreezemobs-fabric: Snowballs Freeze Mobs (Fabric) 1.9
		sodium: Sodium 0.2.0+build.4
		sodium-extra: Sodium Extra 0.4.6+mc1.16.5-build.44
		spark: spark 1.6.0
		speedyhopper: Speedy Hopper 1.0-1.16.5-1
		tooltipfix: ToolTip Fix 1.0.2-1.16
		torohealth: ToroHealth Damage Indicators 1.16.5-fabric-6
		transliterationlib: TRansliterationLib 1.0.4
		trinkets: Trinkets 2.6.7
		worldedit: WorldEdit 7.2.5+57d5ac9
		xaerominimap: Xaero's Minimap 22.13.0
		xaeroworldmap: Xaero's World Map 1.26.2
	Loaded Shaderpack: (off)
	Player Count: 0 / 8; []
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
	Client Crashes Since Restart: 0
	Integrated Server Crashes Since Restart: 1

**Comment by Pyrofab** [comment]
Ah, this looks like an incompatibility with later versions of Fabric API for MC 1.16. This version of the game isn't supported anymore so I'd recommend updating if you can, but otherwise you can try using an *older* version of Fabric API for MC 1.16.
