### ISSUE TITLE
it appears it can't find one of its own classes

### ISSUE THREAD

**Issue by Nathan22211** [Ladysnake/Cardinal-Components-API#135]
https://pastebin.com/aC3YQsCd log (from last crash) crashes on server tick loop had this three times.

This seemed to have happened after I added some mods, but the only mods I have that use CCA are trinkets, on soul fire, and realistic fire spread all of which I disabled. I can send you my curseforge profile if need be.

**Comment by Pyrofab** [comment]
Looks like one of your mods requires the cardinal-components-block module but does not bundle it. You should be able to fix the issue by installing the whole library from [curseforge](curseforge.com/minecraft/mc-mods/cardinal-components) or [modrinth](modrinth.com/mod/cardinal-components-api/).
