### ISSUE TITLE
World components don't auto-sync on load

### ISSUE THREAD

**Issue by l-Luna** [Ladysnake/Cardinal-Components-API#136]
Because `ComponentsWorldNetworking` checks for the now-superceded `fabric-networking-v0`, world components (that implement `AutoSyncedComponent`) won't get synced if the new `fabric-networking-api-v1` is present instead. The actual callback implementation still works, it just isn't run.

**Comment by Pyrofab** [comment]
Oh. Thanks for the heads-up !
