### ISSUE TITLE
Crash on 1.19 with Adorn v3.6.1 and API v5.0.2

### ISSUE THREAD

**Issue by TalEdd** [Ladysnake/Cardinal-Components-API#138]
It causes the launcher to crash on 1.19, with errors provided by 'adorn'. I was using the latest version 5.0.2, if I downgrade to 5.0.1, everything works fine again and launches properly.

[crash-2022-08-28_19.29.20-client.txt](https://github.com/OnyxStudios/Cardinal-Components-API/files/9439558/crash-2022-08-28_19.29.20-client.txt)
[crash-2022-08-28_19.26.37-client.txt](https://github.com/OnyxStudios/Cardinal-Components-API/files/9439559/crash-2022-08-28_19.26.37-client.txt)

**Comment by Surpos0** [comment]
i have same issue but instead of adorn, my crash log is telling me that alloy forgery is a problem.

**Comment by Pyrofab** [comment]
Unmarked 5.0.2 as compatible with 1.19.0, apologies for the inconvenience.
