### ISSUE TITLE
Crash on client (1.19.2, fabric loader 0.14.9, cardinal-api: 5.0.1)

### ISSUE THREAD

**Issue by AmibeSkyfy16** [Ladysnake/Cardinal-Components-API#139]
Note version 5.0.2 didnt crash anymore. So i think it fixed. a tiny problem still there, Curseforge application will automatically download 5.0.1, maybe because 5.0.2 it is not tagged for 1.19.2

logs: https://pastebin.com/sjfJ0NHL

**Comment by Pyrofab** [comment]
Version 5.0.2 is now tagged for 1.19.2

**Comment by AmibeSkyfy16** [comment]
Thanks !
