### ISSUE TITLE
incompatible with sodium

### ISSUE THREAD

**Issue by Littleevo** [Ladysnake/Cardinal-Components-API#140]
whenever this library is loaded with sodium, the game crashes at startup. crash file located below
[crash-2022-09-27_21.45.47-client.txt](https://github.com/OnyxStudios/Cardinal-Components-API/files/9658679/crash-2022-09-27_21.45.47-client.txt)

**Comment by Pyrofab** [comment]
Err, I'm not sure how the sodium error happens, but version 5.0.2 of CCA is not compatible with MC 1.19.0. Could you try again with version 5.0.1 ?
