### ISSUE TITLE
Wrong file marked as primary in 5.0.2 Modrinth release

### ISSUE THREAD

**Issue by raws** [Ladysnake/Cardinal-Components-API#141]
Hi there! I noticed that [Cardinal Components 5.0.2 on Modrinth](https://modrinth.com/mod/cardinal-components-api/version/5.0.2) has `cardinal-components-base-5.0.2.jar` marked as the primary file—should that be `cardinal-components-api-5.0.2.jar` instead, as with [previous releases](https://modrinth.com/mod/cardinal-components-api/version/5.0.1)? It seems to be causing clients that use Modrinth's API, such as [packwiz](https://github.com/packwiz/packwiz), to grab the wrong file for most folks downloading it as a dependency.

Thanks for maintaining this!

**Comment by UpcraftLP** [comment]
Fixed, thanks.
