### ISSUE TITLE
Synchronization how

### ISSUE THREAD

**Issue by Ayutac** [Ladysnake/Cardinal-Components-API#146]
Hi there,

I think https://github.com/OnyxStudios/Cardinal-Components-API/wiki/Making-custom-component-providers is mostly outdated. I added AutoSyncedComponent to my Component, do I need to implement anything else? (Because it feels like the sync is only done once upon entering the world)

**Comment by Pyrofab** [comment]
I do not think it is outdated, but it's specifically about making new component *providers* (so like, `Chunk` and `Entity` are component providers, you could make a new category of objects that can have components attached). The sync is indeed done only once by default, more information is available on the [Synchronizing components](https://github.com/OnyxStudios/Cardinal-Components-API/wiki/Synchronizing-components) page

**Comment by Ayutac** [comment]
Alright, I didn't see the synchronization link, my bad
