### ISSUE TITLE
incompatibilities and crashes with Optifine/Optifabric

### ISSUE THREAD

**Issue by itsMarkiS** [Ladysnake/Cardinal-Components-API#148]
when using something with cardinalcomponents api, the game wont start if youre using the last optifines version

**Comment by bvhfve** [comment]
Same issue, can confirm in 1.19.2
I think it's specifically just the cardinal component blocks api that is incompatible

**Comment by Pyrofab** [comment]
Fixed in https://github.com/Chocohead/OptiFabric/pull/987
