### ISSUE TITLE
Allow registering world components on certain dimensions

### ISSUE THREAD

**Issue by AlphaMode** [Ladysnake/Cardinal-Components-API#151]
Currently if you want to attach a world component your forced to register it for all dimensions.
Adding a method to WorldComponentFactoryRegistry like register(ComponentKey<C> type, Identifier dimensionId, ComponentFactory<World, ? extends C> factory) could solve this

**Comment by Pyrofab** [comment]
Sounds doable - what would be your use case ?

**Comment by Redfan2** [comment]
Hello @AlphaMode, have you come to a solution in the meantime? If you ended up implementing the proposed features yourself, would you mind PRing them?

**Comment by AlphaMode** [comment]
Sorry I forgot about this issue, but I still don't have a proper solution for this. My use case is here https://github.com/The-Aether-Team/The-Aether/blob/1.20.1-develop/src/main/java/com/aetherteam/aether/capability/time/AetherTimeCapability.java I'm in charge of the fabric port and I want to attach this component only to the aether dimension

**Comment by Pyrofab** [comment]
Ah right, well the workaround right now is to make a dummy implementation of the component and attach that to everything that is not your dimension

**Comment by AlphaMode** [comment]
Are there any plans to implement this?

**Comment by Pyrofab** [comment]
I may do it for the MC 1.20.5 update but no promise

**Comment by Pyrofab** [comment]
Well, I did it 😎
