### ISSUE TITLE
Package documentation references the removed BlockComponentProvider class

### ISSUE THREAD

**Issue by haykam821** [Ladysnake/Cardinal-Components-API#159]
The documentation for the `dev.onyxstudios.cca.api.v3.block.util` package doesn't seem right, since the `BlockComponentProvider` class no longer exists:

https://github.com/OnyxStudios/Cardinal-Components-API/blob/a7891cf786289b1ce8249ef6f26228520cb788df/cardinal-components-block/src/main/java/dev/onyxstudios/cca/api/v3/block/util/package-info.java#L23-L26

**Comment by Pyrofab** [comment]
Looks like the remainders of an old API I forgot to remove
