### ISSUE TITLE
please mark it on modrinth as client side required

### ISSUE THREAD

**Issue by Karotte128** [Ladysnake/Cardinal-Components-API#170]
This mod is marked as server-side only on modrinth but modpacks do not work without it being installed on the client. At least the version for 1.20.1 is affected.

**Comment by Pyrofab** [comment]
That is the case for most modpacks, but it depends on which mods use Cardinal Components API. There are mods which use CCA while being serverside only.

**Comment by Pyrofab** [comment]
Ah I see, it was marked as unsupported clientside, but it should be optional instead. Should be good now.

**Comment by bravely-beep** [comment]
This is currently listed as "Supported environments: Server-side" only. Seems to be a regression caused when Modrinth changed their tagging system? This should probably be marked as supporting both sides.
