### ISSUE TITLE
6.0.0-pre1 uses loom 1.7 alpha

### ISSUE THREAD

**Issue by jpenilla** [Ladysnake/Cardinal-Components-API#175]
Is it intentional that the published builds for 6.0.0-pre1 are built using loom 1.7 alpha? This forces consumers to update to loom 1.7 alpha as well: https://github.com/jpenilla/squaremap/pull/227. What's strange is the repo doesn't use 1.7: https://github.com/Ladysnake/Cardinal-Components-API/blob/1.20.5/build.gradle.kts#L7, but downloading the jar from releases or maven and checking the manifest shows that it was in fact built with 1.7.

**Comment by Pyrofab** [comment]
Not intentional, it's most likely being pulled as a transitive dependency. Apologies for the inconvenience.

**Comment by Pyrofab** [comment]
Fixed in pre2
