### ISSUE TITLE
Crashing problems

### ISSUE THREAD

**Issue by KozukiYOMA** [Ladysnake/Cardinal-Components-API#176]
I get a crash caused by Cardinal-Components-API, but I don't know what is causing it. I would like to know which mod is causing the problem and whether the problem can be fixed on the Cardinal-Components-API side.
[latest.log](https://github.com/Ladysnake/Cardinal-Components-API/files/15408211/latest.log)
[crash-2024-05-23_05.06.34-client.txt](https://github.com/Ladysnake/Cardinal-Components-API/files/15408214/crash-2024-05-23_05.06.34-client.txt)

**Comment by Pyrofab** [comment]
Hello, I believe the bossbar mod is not updated for 1.20.5 and up. That is not an issue we can fix on our end.

**Comment by Pyrofab** [comment]
Actually no, the modrinth page says it is...? But it was not compiled using the right version that's for sure - and since it is closed source, I can't really check
