### ISSUE TITLE
joining a server that has this mod on a vanilla client wont let me join

### ISSUE THREAD

**Issue by Elyas2024** [Ladysnake/Cardinal-Components-API#181]
i tried joining my server on localhost to test an update im tryna push to my smp, i joined on a client with only client side mods. it said i need the cardinal components api mod to join.

**Comment by Pyrofab** [comment]
Did you use `AutoSyncedComponent` somewhere in your mod ? If so, you need to override `isRequiredOnClient`.

**Comment by Recreabox** [comment]
Thank you, but i can't find "how to override isRequireOnClient".
Please can you explain ?

**Comment by Pyrofab** [comment]
Sorry for the delay, I missed your question. The wiki has an example : https://ladysnake.org/wiki/cardinal-components-api/synchronization#client-optional-components
