### ISSUE TITLE
v6.2.0 publication is broken

### ISSUE THREAD

**Issue by jpenilla** [Ladysnake/Cardinal-Components-API#186]
It seems like the metadata for 6.2.0 is missing, see https://maven.ladysnake.org/#/releases/org/ladysnake/cardinal-components-api/cardinal-components-entity/6.2.0 vs https://maven.ladysnake.org/#/releases/org/ladysnake/cardinal-components-api/cardinal-components-entity/6.1.2

I'm also not able to resolve it with gradle

**Comment by Pyrofab** [comment]
Darn, sorry, should be good now

**Comment by jpenilla** [comment]
Can confirm it resolves properly now, thanks!
