### ISSUE TITLE
Cardinal Components API

### ISSUE THREAD

**Issue by vurfex** [Ladysnake/Cardinal-Components-API#189]
I have problem with Cardinal Components API on my minecraft server (fabric) this communicat show up "This server requires Cardinal Components API (unhandled packet: cardinal-components:entity_sync)"

**Comment by Xiribidus** [comment]
Send your latest.log please

**Comment by Pyrofab** [comment]
If this is about Impersonate, it has been fixed in the latest release. If it is about another mod, you should send them this link: https://ladysnake.org/wiki/cardinal-components-api/upgrade-instructions/CCA-6-changes#client-optional-components
