### ISSUE TITLE
Early chunk component initialization

### ISSUE THREAD

**Issue by Stuff-Stuffs** [Ladysnake/Cardinal-Components-API#29]
Chunk components are initialized in [MixinChunk#L47](https://github.com/OnyxStudios/Cardinal-Components-API/blob/e8330a4c880c9b66487fb74412469667431900d5/cardinal-components-chunk/src/main/java/dev/onyxstudios/cca/mixin/chunk/common/MixinChunk.java#L47), this happens before the chunk constructor has ran. This causes any field access of the chunk, such as getWorld() or getPos(), to return null.

**Comment by Pyrofab** [comment]
Do you actually need those methods in your component's constructor ? In most cases, you can have lazy initialization. Still, I will try to change that for 1.16.

**Comment by Stuff-Stuffs** [comment]
Not really that big of an issue, I just wrap them in Lazy. Still it does catch you off guard, if not fixed it should just be documented.
