### ISSUE TITLE
Item Components disappearing on 2.4.0-nightly.1.16-rc1.build.2

### ISSUE THREAD

**Issue by Draylar** [Ladysnake/Cardinal-Components-API#30]
I'm using **2.4.0-nightly.1.16-rc1.build.2** with [Universal Components](https://github.com/CottonMC/UniversalComponents) **0.7.2+1.16-pre2** on **1.16 release**.  Upon dropping my item, which uses a UC `InventoryComponent` (and picking it back up), the data is wiped. The only change between my old mod version (working) and the new version (not working) was going from CCA `2.4.0-nightly.1.16-pre2` to `2.4.0-nightly.1.16-rc1.build.2` (UC stayed on the same version). 

This occurs in production and in dev. I'm pulling both dependencies like this:
```groovy
// bob's cardinal components 2
modCompile "io.github.cottonmc:UniversalComponents:${project.universal_components_version}"
include "io.github.cottonmc:UniversalComponents:${project.universal_components_version}"

// go cornmit jij
modCompile "io.github.OnyxStudios:Cardinal-Components-API:${project.cardinal_components_version}"
```
```groovy
universal_components_version=0.7.2+1.16-pre2
cardinal_components_version=2.4.0-nightly.1.16-rc1.build.2
```
I asked in the UC channel and bob said it was most likely CCA. I tried to step around with the debugger, but I couldn't find any leads on the issue.

**Comment by Pyrofab** [comment]
~~Probably Mojang doing stupid again...~~ Nop, I did the stupid. Fix coming soon.

**Comment by Draylar** [comment]
Works great, thanks again for the fix!
