### ISSUE TITLE
Crash on 1.16.1 

### ISSUE THREAD

**Issue by shaterrr** [Ladysnake/Cardinal-Components-API#35]
No matter if there any mods or it only with Cardinal Components
[crash-2020-07-14_23.27.05-client.txt](https://github.com/OnyxStudios/Cardinal-Components-API/files/4921168/crash-2020-07-14_23.27.05-client.txt)

**Comment by zimdin12** [comment]
Same here

**Comment by Pyrofab** [comment]
Ah, that's the Optifine crash. There will be a fix soon.

**Comment by Pyrofab** [comment]
Fixed in bfc9b63c85d9b7d79d48154b98e4d98dd3d685b7 ([v2.4.2](https://github.com/OnyxStudios/Cardinal-Components-API/releases/tag/2.4.2))
