### ISSUE TITLE
Add example of static component registration metadata to wiki/readme

### ISSUE THREAD

**Issue by Nosrick** [Ladysnake/Cardinal-Components-API#37]
Hi there,
I'm trying to register a static component, and it keeps complaining that the component isn't registered via mod metadata, or a plugin.

I can't find any documentation for doing this.

**Comment by UpcraftLP** [comment]
did you follow the wiki article on [attaching components](https://github.com/OnyxStudios/Cardinal-Components-API/wiki/Attaching-components)?

If yes, could you show exactly what your code looks like, as well as attach a full error log?

**Comment by Nosrick** [comment]
Yeah, I did.

The wiki article doesn't specify anywhere that static components need to be registered through mod metadata or plugin.

Even in the testmod, I can't figure out how it manages to get a static component working.

Here's my Component container.
https://hastebin.com/igezohugor.java

And the only Component implementing interface I have:
https://hastebin.com/zelefepate.java

If you need more code, just say and I'll hastebin it!

And here's my error log:
https://hastebin.com/ajucotikib.cs

**Comment by Nosrick** [comment]
I did actually find where it references the static registration, I just had it in the wrong place!

Sorry about that. You can probably close/delete this issue.
