### ISSUE TITLE
Block Entity support

### ISSUE THREAD

**Issue by williewillus** [Ladysnake/Cardinal-Components-API#40]
I might be missing something, but there doesn't seem to be an easy way to add components to block entities.

Although block components bounce to the BE if it implements BlockComponentProvider, support does not seem first class in the way it seems to be for e.g. Entities. From what I can tell, attaching mod components to something like vanilla's block entities seems impossible.

Is there a reason that this doesn't exist?

**Comment by LemmaEOF** [comment]
I'm going to look into this.

**Comment by Pyrofab** [comment]
This is true, block components are currently second-class. I am aiming to fix that in the next release, for 1.16.2. (see the feature/block-v3 branch)

**Comment by LemmaEOF** [comment]
...oh.
