### ISSUE TITLE
Wiki codes out-of-date?

### ISSUE THREAD

**Issue by yuesha-yc** [Ladysnake/Cardinal-Components-API#44]
MC version: 1.16.1 
Cardinal Components Version: 2.4.2

Hi I tried the wiki example to register a component. I have a question regarding this. 
```
public class Handler_Components implements EntityComponentInitializer {

    public static final ComponentType<IComponentFloat> FLOAT_COMPONENT_TYPE =
            ComponentRegistry.INSTANCE.registerIfAbsent(new Identifier("eltcore:float"), IComponentFloat.class);

    @Override
    public void registerEntityComponentFactories(EntityComponentFactoryRegistry registry) {
        registry.register(FLOAT_COMPONENT_TYPE, IComponentFloat::new);
    }
}
```
This method does not work because it requires three components. 
`registry.register(FLOAT_COMPONENT_TYPE, IComponentFloat::new);
`
And my entry point is added. 
```
"entrypoints": {
    "cardinal-components-entity": [
      "net.moeg.eltcore.handlers.Handler_Components"
    ]
  },
```

I saw in the source saying that many of these above methods are experimental or scheduled to be removed. Can you recommend a stable version to use Cardinal-Components-API? I like the mod's utility very much.

**Comment by UpcraftLP** [comment]
> This method does not work because it requires three components.

Entity components require you to tell the API what type of entity the component should be attached to, by passing the entity class. see the [javadoc comment on that interface](https://github.com/OnyxStudios/Cardinal-Components-API/blob/master/cardinal-components-entity/src/main/java/dev/onyxstudios/cca/api/v3/component/entity/EntityComponentFactoryRegistry.java#L54-L69).


> I saw in the source saying that many of these above methods are experimental or scheduled to be removed.

The V3 api is somewhat in flux still, it will be promoted to stable in 1.17.
If you don't want that, use the old way of registering component factories via the respective events instead.
