### ISSUE TITLE
Crash when starting worlds

### ISSUE THREAD

**Issue by thomaskorstanje** [Ladysnake/Cardinal-Components-API#48]
Having a problem while trying to start a world with Fabric that relates to this...I think. Any ideas? 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2020-08-26 15:29:10 EDT
Description: Exception in server tick loop

java.lang.NoSuchMethodError: dev.onyxstudios.cca.internal.base.DynamicContainerFactory.create(Ljava/lang/Object;)Lnerdhub/cardinal/components/api/component/ComponentContainer;
    at Not Enough Crashes deobfuscated stack trace.(1.16.1+build.21)
    at net.minecraft.world.World.handler$bhd000$initComponents(World:3791)
    at net.minecraft.world.World.<init>(World:158)
    at net.minecraft.server.world.ServerWorld.<init>(ServerWorld:180)
    at net.minecraft.server.MinecraftServer.createWorlds(MinecraftServer:368)
    at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer:334)
    at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer:69)
    at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:647)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:256)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.1
  Minecraft Version ID: 1.16.1
  Operating System: Mac OS X (x86_64) version 10.15.6
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 6341600792 bytes (6047 MB) / 8556380160 bytes (8160 MB) up to 8589934592 bytes (8192 MB)
  CPUs: 8
  JVM Flags: 8 total; -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Unknown
  Fabric Mods: adorn: Adorn 1.10.1+1.16.1
               allure: Allure 1.2.1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               artifice: Artifice 0.8.0+1.16-rc1
               atmosfera: Atmosfera 1.2.2-1.16
               autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
               automated_crafting: Automated Crafting 1.3.4+1.16.1
               autoswap: Autoswap 1.16-fabric0.13.1-1.0.1
               bambootweaks: Bamboo Tweaks unspecified
               battletowers: Battle Towers 3.0.3-beta-1.16.1
               bedspreads: Bedspreads 1.0.0-1.16.1
               betterdroppeditems: Better Dropped Items 1.2.1-1.16
               blackstonetools: Blackstone Tools 1.2.0+1.16.1
               blue_endless_jankson: jankson +
               boot: BootZ 1.3.1
               byg: BYG 1.0.13
               campanion: Campanion 1.1.13+build.35
               can-i-mine-this-block: can i mine this block? 1.0.0
               cardinal-components-base: Cardinal Components API (base) 2.5.0
               cardinal-components-entity: Cardinal Components API (entities) 2.5.0
               cardinal-components-world: Cardinal Components API (worlds) 2.4.0-nightly.1.16-rc1.build.2
               chainmail: Chainmail 0.5.0
               cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.0.5
               cloth-config2: Cloth Config v4 4.6.0
               controlling: Controlling For Fabric 1.1.2
               cotton: Cotton 1.0.7
               cotton-cauldron: Cotton Cauldron 1.0.4
               cotton-client-commands: Cotton Client Commands 1.0.0+1.15.2
               cotton-commons: Cotton Commons 1.0.4
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-datapack: Cotton Datapack 1.0.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               cotton-player-events: Cotton Player Events 1.0.2
               couplings: Couplings 1.3.1
               crimsonmoon: Crimson Moon 1.2.2-1.16.1
               crookedcrooks: Crooked Crooks 1.2.1+1.16.1
               dark-loading-screen: Dark Loading Screen 1.4.2
               diggusmaximus: Diggus Maximus 1.3.0-1.16
               dishes: Delicious Dishes 1.0.3
               dynamicfps: Dynamic FPS 1.1.4
               dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
               earthtojavamobs: Earth2Java 1.1.0+1.16.1
               ecotones: Ecotones 0.5.1
               endreborn: End: Rebellion 1.7.1
               expandedconcrete: Expanded Concrete 0.0.1
               expandedstorage: ExpandedStorage 5.5.22
               fabric: Fabric API 0.17.0+build.386-1.16.1
               fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
               fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
               fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
               fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
               fabric-language-kotlin: Fabric Language Kotlin 1.3.71+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
               fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
               fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
               fabricloader: Fabric Loader 0.9.2+build.206
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.2
               fatxporbs: Fat Experience Orbs 0.0.7
               fiber: fiber 0.23.0-1
               flesh2leather: Flesh2Leather 1.0.0
               flonters: Flonters 1.1.0+1.16.1
               harvest: Harvest 1.2.12
               horseinfo: Horse Info 0.2.2-1.16.1
               illuminations: Illuminations 1.0.4
               intotheomega: Into the Omega 1.0.3-beta-1.16.1
               inventoryprofiles: Inventory Profiles 0.4.2
               jankson: Jankson 3.0.0+j1.2.0
               kibe: Kibe 1.1.12-BETA
               kyrptconfig: Kytpt Config 1.1.0-1.16
               libcd: LibCapableData 2.5.0+1.16.1
               libgui: LibGui 2.3.0+1.16.1
               libstructure: Libstructure 1.3
               lightoverlay: Light Overlay 5.4.2
               linkedstorage: Linked Storage 1.3.6-1.16
               lithium: Lithium 0.5.1
               loadcatcher: Entrypoint Catcher 2.0.0
               magna: Magna 1.3.2-1.16.1
               mambience: MAmbience 2.1.0-1.16
               mattocks: Mattocks 1.0.3
               mdp: MusicDiscsPlus 1.0.0-FABRIC.1.16.1
               mighty_mangoes: Mighty Mangoes 1.0.0
               minecraft: Minecraft 1.16.1
               mm: Manningham Mills 2.0
               mo_glass: Mo Glass 1.3-MC1.16.1
               modmenu: Mod Menu 1.14.5+build.30
               moreberries: More Berries 1.3.1
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.0
               mostructures: Mo' Structures 1.0.0-pre2+mc.1.16
               netheritehorsearmor: Netherite Horse Armor 0.4.2-1.16.1
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               org_apache_httpcomponents_httpclient: httpclient 4.5.10
               org_apache_httpcomponents_httpcore: httpcore 4.4.12
               org_apache_httpcomponents_httpmime: httpmime 4.5.10
               org_codehaus_groovy_groovy: groovy 3.0.3
               org_codehaus_groovy_groovy-jsr223: groovy-jsr223 3.0.3
               org_jetbrains_annotations: annotations 17.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.71
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.71
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.5
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.5
               origins: Origins 1.16-0.3.4
               origins-classes: Origins: Classes 1.16.1-1.0.1
               packages: Packages 1.0
               packed: Packed Storage 1.0.7
               parchment: Parchment 1.0.2+1.15.2
               patchouli: Patchouli 1.16-39-FABRIC
               petowner: Pet Owner 1.16.1-1.3
               phosphor: Phosphor 0.6.0+build.7
               playerabilitylib: Pal 1.2.0
               portalcrafter: Portal Crafter 1.0.0
               pumice: Pumice 0.0.1
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               repurposed_structures: Repurposed Structures 1.4.6
               respawnablepets: Respawnable Pets 4
               roughlyenoughitems: Roughly Enough Items 4.12.1
               roughlyenoughresources: Roughly Enough Resources 2.0.2
               rpgstats: RPGStats 2.1.4+1.16.1
               satin: Satin 1.4.0-nightly.1.16-pre5+build.1
               secretrooms: Secret Rooms 0.9.1+1.16.1
               shapes: Shapes 2.0.0+build.10
               shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
               sign_editor: Better Signs & Frames mc-1.16.1-0.6.1
               silky_spawners: Silky Spawners 2.0.0+build.1-1.16
               simpledrawers: Simple Drawers 1.8.0-1.16.1
               simplexterrain: Simplex Terrain 0.6.5
               simplyplatinum: Simply Platinum 2.0.0
               skinswapper: Minecraft Skin Change Mod 2.0.1
               slabhelper: Slab Helper 1.3.2
               slight-gui-modifications: 'Slight' GUI Modifications 1.2.0
               sodium: Sodium 0.1.0
               soulbound: Soulbound 1.0.1
               spinnery: Spinnery 3.1.14
               staffofbuilding: Staff of Building 1.2.0-1.16
               static-content: Static Content 1.0.0-1.16.1
               staticdata: Static Data 1.1.2
               stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
               structure-helpers: Structure Helpers 2.1.0
               stuffz: StuffZ 2.2.2
               tacocraft: TacoCraft 1.3.1+mc.1.16
               terraform: Terraform 2.3.0+build.33
               terrestria: Terrestria 2.0.6+build.58
               the_bumblezone: The Bumblezone - Fabric 1.16.1-2.1.2
               toms_storage: Tom's Simple Storage Mod 1.1.1
               tomsfabriclibs: Tom's Fabric Lib 1.0.2
               torridvision: Torrid Vision 0.0.1
               trash-it: Trash It 1.0.1-1.16.1
               traverse: Traverse 2.2.15+build.30
               trinkets: Trinkets 2.6.3
               umollu_ash: ASH - Another Simple HUD 1.1.9
               unlimiteddragoneggs: Unlimited Dragon Eggs 1.0.0
               vanilla-hammers: Vanilla Hammers 2.0.4-1.16.1
               vanillaexcavators: Vanilla Excavators 1.1.0
               villagerhats: Villager Hats fabric-1.16-rc1-1.0.0
               waila: Hwyla 1.9.22
               wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
               woods_and_mires: Woods and Mires 1.0.0+1.16.1
               xaeroworldmap: Xaero's World Map 1.10.1
  Patchouli open book context: n/a
  Player Count: 0 / 8; []
  Data Packs: vanilla (incompatible), fabric/kibe (incompatible), fabric/packages, fabric/villagerhats, fabric/mo_glass, fabric/morecraftingtables, fabric/repurposed_structures, fabric/battletowers, fabric/structure-helpers, fabric/mostructures, fabric/origins, fabric/adorn, fabric/the_bumblezone, fabric/toms_storage, fabric/terrestria, fabric/linkedstorage, fabric/expandedconcrete, fabric/vanillaexcavators, fabric/portalcrafter, fabric/netheritehorsearmor, fabric/wolveswitharmor, fabric/ecotones, fabric/bambootweaks, fabric/intotheomega, fabric/woods_and_mires, fabric/cotton-commons, fabric/origins-classes, fabric/packed, fabric/boot, fabric/harvest, fabric/byg, fabric/cinderscapes, fabric/silky_spawners, fabric/staffofbuilding, fabric/rpgstats, fabric/blackstonetools, fabric/respawnablepets, fabric/pumice, fabric/simpledrawers, fabric/tacocraft, fabric/fabric-tool-attribute-api-v1, fabric/endreborn, fabric/expandedstorage, fabric/dishes, fabric/earthtojavamobs, fabric/trash-it, fabric/libcd, fabric/flesh2leather, fabric/vanilla-hammers, fabric/allure, fabric/automated_crafting, fabric/flonters, fabric/campanion, fabric/bedspreads, fabric/traverse, fabric/mdp, fabric/moreberries, fabric/crookedcrooks, fabric/stuffz, fabric/simplyplatinum, fabric/slabhelper, fabric/mattocks, fabric/mighty_mangoes, fabric/secretrooms, global/cotton_generated (incompatible), linkedstorage:enderstorage, secretrooms:server_pack
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by Pyrofab** [comment]
Oh, you got a mod that packages an outdated version of `cardinal-component-world`. If you can find which mod, I'd recommend telling the author. As a workaround, you can download the [full library separately](https://github.com/OnyxStudios/Cardinal-Components-API/releases/tag/2.5.2) and put it in your mods directory.

**Comment by thomaskorstanje** [comment]
> Oh, you got a mod that packages an outdated version of `cardinal-component-world`. If you can find which mod, I'd recommend telling the author. As a workaround, you can download the [full library separately](https://github.com/OnyxStudios/Cardinal-Components-API/releases/tag/2.5.2) and put it in your mods directory.

How would I go about finding it? Thanks for the quick response! edit: I also downloaded and but the full library into the mods directory and the same bug happened.

**Comment by Pyrofab** [comment]
Did you download `Cardinal-Components-API-2.5.2.jar` ? Could you share a new log ?

**Comment by thomaskorstanje** [comment]
> Did you download `Cardinal-Components-API-2.5.2.jar` ? Could you share a new log ?

GOT IT. Thank you for your help! I was an idiot and accidentally added both APIs. Thanks!
