### ISSUE TITLE
2.5.0+ Crash with Amecs

### ISSUE THREAD

**Issue by Rongmario** [Ladysnake/Cardinal-Components-API#49]
- Minecraft Version: 1.16.2

- Cardinal Components API Tested Version: 2.5.0, 2.5.1 and 2.5.2 (works with 2.4.2 or below)
- Amecs API Tested Version: 1.0.2 and 1.0.3

Crash: https://gist.github.com/Rongmario/8912ebe70089a4274e650f1dce969a84

Edit: this was in dev, have not tested outside dev.

**Comment by Pyrofab** [comment]
Try updating Amecs, latest version is 1.3.1 for MC1.16.1. I can confirm that both run together outside a development environment.

**Comment by Rongmario** [comment]
My bad, did not specify that Amecs version was for the *API* not the mod, the API I believe has a different versioning, latest is 1.0.3. https://maven.siphalor.de/de/siphalor/amecsapi-1.16/

**Comment by Pyrofab** [comment]
After further testing, I can tell you that Amecs crashes in a dev environment without CCA, so you should probably report this to Siphalor instead.

**Comment by Rongmario** [comment]
Already reported to Siphalor, and we've tested it where it does not crash by itself. Do also check Mouse Wheelie for an Amecs project that runs successfully in dev and has latest Amecs.
