### ISSUE TITLE
Game Crash on World Load

### ISSUE THREAD

**Issue by enderger** [Ladysnake/Cardinal-Components-API#50]
# Game Crash on World Load
Whenever I load a world in a dev environment while working on my mod (it uses the V3 API), I recieve the following crash: https://controlc.com/ee04be1d

---
### Reproduction Steps
Unfortunately, as my mod is not production ready as of yet, I am not ready to share the source code. I don't know what causes the crash

---
### System Info
OS: Bedrock Linux
CC Version:  2.5.2
Modules in use: Base, Chunk
MC Version: 1.16.2
All other details can be extracted from the crash report

**Comment by Pyrofab** [comment]
Oh wow that's a dumb bug. Thanks for reporting.
