### ISSUE TITLE
CC Chunk (and maybe Base) have dependency on CC Entity

### ISSUE THREAD

**Issue by enderger** [Ladysnake/Cardinal-Components-API#51]
# CC Chunk (and maybe Base) have dependency on CC Entity
---

Hi, recently you patched a dependency issue with CC Chunk. I've found another one, where it appears to also be dependant on the Entity module. Worlds only load if entity is present.

**Comment by Pyrofab** [comment]
How do I keep doing this... Can I get a stacktrace ?

**Comment by enderger** [comment]
Ok, here: https://controlc.com/1412204d

**Comment by Pyrofab** [comment]
Ah no, this is an unrelated bug. You just have an ancient version of `cardinal-components-entity`, same as #48. Easy fix is to download the full library and put it in your mods folder.

**Comment by enderger** [comment]
My mod only works if I add entity in Gradle, and the only cause could be my use of Trinkets API

**Comment by Pyrofab** [comment]
Ah, gradle being shit again. Try something like:
```gradle
modImplementation("whatever:trinket:xxx") {
    transitive = false
}
```
Edit: I kind of misunderstood the issue. You need to add entity in gradle, not because cca-chunk relies on it, but because trinkets relies on an old incompatible version.
