### ISSUE TITLE
Mixin conflicts with Immersive Portals

### ISSUE THREAD

**Issue by qouteall** [Ladysnake/Cardinal-Components-API#52]
https://github.com/OnyxStudios/Cardinal-Components-API/blob/master/cardinal-components-block/src/main/java/dev/onyxstudios/cca/mixin/block/common/MixinThreadedAnvilChunkStorage.java

and

https://github.com/OnyxStudios/Cardinal-Components-API/blob/master/cardinal-components-chunk/src/main/java/dev/onyxstudios/cca/mixin/chunk/common/MixinThreadedAnvilChunkStorage.java

have mixin conflicts with
https://github.com/qouteall/ImmersivePortalsMod/blob/1.16/imm_ptl_core/src/main/java/com/qouteall/immersive_portals/mixin/common/chunk_sync/MixinThreadedAnvilChunkStorage_C.java#L120

Solution: Mixin allows injecting into an overwritten method. I am going to change my mixin's priority to higher and ensure that vanilla calls of sendChunkDataPackets won't get intercepted. Cardinal components need to change `cardinal-components-block/MixinThreadedAnvilStorage`'s injection point to `RETURN`

**Comment by Pyrofab** [comment]
Ah, I already had a fix for this - fc0971e767a66450d1e68ea968282e2172d20df9
But your solution is cleaner so by all means, go ahead.
