### ISSUE TITLE
Attempting to create an ItemStack while registering an ItemStack component crashes the game

### ISSUE THREAD

**Issue by SilverAndro** [Ladysnake/Cardinal-Components-API#58]
Minecraft Version: 1.16.3
CCA Version: 2.6.0
CCA Modules: base, item

Attempting to create an ItemStack while registering an ItemStack component crashes the game with the following error https://paste.ee/p/exs70

This can occur non-deliberately by loading a class that, for example, attempts to build an ItemGroup in \<clinit> which results in
`Caused by: java.lang.NullPointerException
	at net.fabricmc.fabric.api.client.itemgroup.FabricItemGroupBuilder.build(FabricItemGroupBuilder.java:100)` at the bottom of the previously linked error

I have created what appears to be the minimum required to reproduce at https://github.com/P03W/CCA_Crash

**Comment by Pyrofab** [comment]
Thanks for the detailed report ! This is a known issue, and it should be hopefully fixed with the next version.
