### ISSUE TITLE
MIT License for Cardinal Components not included when using Jar in Jar

### ISSUE THREAD

**Issue by Levoment** [Ladysnake/Cardinal-Components-API#68]
Hi

I was following the instructions to use cardinal components on my mod. When I built the JAR with this on build.gradle

	repositories {
		maven {
			name = "Ladysnake Libs"
			url = "https://dl.bintray.com/ladysnake/libs"
		}
	}
       ...
	// Cardinal Components
	modImplementation "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:${project.cardinal_components_version}"
	include "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-base:${project.cardinal_components_version}"
	modImplementation "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-entity:${project.cardinal_components_version}"
	include "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-entity:${project.cardinal_components_version}"
	modImplementation "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-world:${project.cardinal_components_version}"
	include "io.github.onyxstudios.Cardinal-Components-API:cardinal-components-world:${project.cardinal_components_version}"

three jars were included on the build on the **/META-INF/jars/** path of my mod jar. Cardinal Components Base, Cardinal Components Entity, and Cardinal Components World. When I checked each of the jars, none of them had the MIT license of cardinal components included on their jars. I'm using the version 2.7.3 of cardinal components, but a few previous versions and later versions also don't include the license in them.

Usually, when mods are included Jar in Jar, each library used includes the library license in the jar themselves.

**Comment by Pyrofab** [comment]
The license is still in the `fabric.mod.json`. I really don't think it's super necessary to copy the license file in every module, but I guess it can be done.
