### ISSUE TITLE
Component equality is ingored when merging itemstacks.

### ISSUE THREAD

**Issue by Frontrider** [Ladysnake/Cardinal-Components-API#69]
Component data is ignored when merging stacks inside the inventory. This bug happens, if we attached a component to an item that can stack.
If 2 with the same id but different data are given to the player it merges. The data from the stack that was in the slot we inject into is copied to the items you add to it, even if a new stack is created (from an overflow)

Video:
https://cdn.discordapp.com/attachments/742703385584730183/784955984392486982/cardinal-item-bug.mp4

**Comment by Pyrofab** [comment]
This has been found to be an issue with NBT Crafting. It should be fixed in NBT Crafting 2.0.3.
