### ISSUE TITLE
Components doesn't work with Swords

### ISSUE THREAD

**Issue by ckevin24** [Ladysnake/Cardinal-Components-API#71]
It seems like my [cca component](https://hatebin.com/yqrtrpurqq) doesn't apply to swords, everything else works for my empty packet item.
The sword supplies the [component](https://hatebin.com/yqrtrpurqq), but when I try write data it doesn't work, but it works for my empty packet item.

If you need anymore information just tell me!
(btw there is nothing in my logs)
![image](https://user-images.githubusercontent.com/54775755/105831725-fdb73780-5fbe-11eb-89f4-92fbca380d68.png)

**Comment by Pyrofab** [comment]
So the component exists on swords, but its data is never saved ? Could I see your registration code ?

**Comment by ckevin24** [comment]
Hello! I'm extremely sorry but I just realised that this is not a cca problem, I have fixed it, I forgot to check something.
Sorry for wasting your time!
Good luck with cca!
