### ISSUE TITLE
server crash with Carpet and cardinal

### ISSUE THREAD

**Issue by drakosoldier298** [Ladysnake/Cardinal-Components-API#72]
https://gist.github.com/drakosoldier298/00b71976e5a2df03664f7b37e930adcc
This is a log from a server on apex so custom.jar is fabric
originally thought to be an issue with an incompatibility between fabrication and carpet but both said it was cardinal components

**Comment by Pyrofab** [comment]
Hmm no it does seem like the issue comes from a carpet mixin. I don't see how CCA could be responsible for a mixin failure.
