### ISSUE TITLE
Bintray deprecation

### ISSUE THREAD

**Issue by parzivail** [Ladysnake/Cardinal-Components-API#74]
Are there any plans to move away from Bintray as a distrbution platform before [its final shutdown on May 1st](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)?

**Comment by UpcraftLP** [comment]
We're looking into several solutions at the moment, such as moving to [Artifactory](https://jfrog.com/artifactory "JFrog Artifactory") free tier, or back to the [OnyxStudios Maven](https://maven.onyxstudios.dev "maven.onyxstudios.dev").

**Comment by Pyrofab** [comment]
Cardinal Components API is now available on Artifactory : https://github.com/OnyxStudios/Cardinal-Components-API/wiki/Installation-(for-developers)#ladysnake-artifactory
