### ISSUE TITLE
[Compat] crash with Automated Crafting

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Ladysnake/Cardinal-Components-API#77]
I'm the dev of Automated Crafting which just had [this issue](https://gitlab.com/supersaiyansubtlety/automated_crafting/-/issues/21) opened. 

I'm pretty sure it's because automated crafting has a `CraftingInventory` with an (unused) `CraftingScreenHandler` with a null player, and Cardinal Components tries to access the null player. 

I can't think of a decent solution to this other than adding a null check in cardinal components, but I'm open to suggestions.

**Comment by UpcraftLP** [comment]
This is an issue with [Requiem](https://github.com/Ladysnake/Requiem "Ladysnake/Requiem"), not CCA.

**Comment by supersaiyansubtlety** [comment]
oh, thanks
