### ISSUE TITLE
Fabric API 0.34.0+1.16/1.17 breaks CCA

### ISSUE THREAD

**Issue by OroArmor** [Ladysnake/Cardinal-Components-API#84]
https://pastebin.com/wwH6xzhw
(Note: not my crash)

I noticed this twice today when helping in #player-support in the Fabric Discord and with the latest fabric api.

**Comment by TrueCP6** [comment]
Similar crash that is present with Fabric API 0.34.0 but not 0.33.1: [crash-2021-05-02_08.17.46-client.txt](https://github.com/OnyxStudios/Cardinal-Components-API/files/6410857/crash-2021-05-02_08.17.46-client.txt)

**Comment by Pyrofab** [comment]
2.8.1 has already been released to fix this crash =)
