### ISSUE TITLE
Cardinal Components API conflicts with Fabric API 30 and above

### ISSUE THREAD

**Issue by YousifTheGamer1** [Ladysnake/Cardinal-Components-API#91]
I saw someone over at the Curseforge page say the same thing and I just came here to confirm that there IS in fact a conflict between both.

Here is the log

[latest.log](https://github.com/OnyxStudios/Cardinal-Components-API/files/6582062/latest.log)
(Apologies if this is already confirmed and solved)

**Comment by UpcraftLP** [comment]
the only issue I see here is that you're using optifine, which is not compatible with cardinal-components-item.

For anything else, please provide a full crash report, and make sure you are using the latest version of cardinal components for your Minecraft version.
