### ISSUE TITLE
Incompatible with newer versions of Fabric API

### ISSUE THREAD

**Issue by LambdAurora** [Ladysnake/Cardinal-Components-API#93]
Newer versions of Fabric API changed `ArrayBackedEvent` and removed the `type` field while CCA gets it in https://github.com/OnyxStudios/Cardinal-Components-API/blob/master/cardinal-components-base/src/main/java/dev/onyxstudios/cca/internal/base/ComponentsInternals.java#L52

This causes significant issues as seen in emilyalexandra/trinkets#100.

**Comment by UpcraftLP** [comment]
This has already been fixed, but trinkets is still using an old version of CCA.

**Comment by LambdAurora** [comment]
Eh, the main branch confused me, sorry!
