### ISSUE TITLE
Run cleanup action

### ISSUE THREAD

**Issue by F0Xde** [Ladysnake/Cardinal-Components-API#95]
Is it possible to execute some action when the component is being removed / unregistered?

**Comment by UpcraftLP** [comment]
Hello,
what exactly do you mean by that?
Components are never unregistered or removed.

**Comment by F0Xde** [comment]
Even when the object it is attached to gets "destroyed"? Like when an entity / chunk / whatever is unloaded?

**Comment by Pyrofab** [comment]
Very late but : you can use Quilt's or Fabric's standard library events for this.
I could add it as a feature to CCA, but it doesn't seem common enough to justify it really.
