### ISSUE TITLE
Chunks Cardinal Components are not persiting between world reloads.

### ISSUE THREAD

**Issue by MalekiRe** [Ladysnake/Cardinal-Components-API#97]
This bug occurs in the 3.0.0 version, and the 3.1.1 version, if one saves and quits a world, and then loads it again, any data saved in chunks with cardiline components is wiped.

**Comment by Pyrofab** [comment]
Just to make sure, you did update the component's value serverside and not clientside right ?

**Comment by gamma-02** [comment]
Uh oh, malek?

**Comment by MalekiRe** [comment]
yes i did

**Comment by Pyrofab** [comment]
Alright I'll try to see what's going on. If you have an idea yourself, PRs are always welcome.

**Comment by MalekiRe** [comment]
If I understood half of how your code worked, I definitely would try and help xD

**Comment by Pyrofab** [comment]
Sorry for not getting around to it, I'm currently really busy IRL... If I haven't fixed it this weekend, please remind me next week.

**Comment by Pyrofab** [comment]
Hmm, I can't reproduce this with CCA's test mod. Could you by any chance give a minimal test case ?

**Comment by MalekiRe** [comment]
https://github.com/Maleks-Modding-Studios/mod-science/blob/master/src/main/java/malek/mod_science/components/chunk/distortion/Distortion.java

My Distortion Doesn't Persist

**Comment by Pyrofab** [comment]
Thanks ! I can confirm the save method never gets called, now to understand why...

**Comment by Pyrofab** [comment]
Alright caught the issue - the chunk's `setShouldSave` command must get called. However it would be a bit complicated for CCA to do it as it has no idea of when a component's state changes... so uh, I guess for now you should call it yourself in one of your setters.

**Comment by Pyrofab** [comment]
Updated the documentation to reflect this, I don't think there's much more we can do currently. Thanks for bringing this issue to my attention !
